CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL CHECK (length(trim(title)) > 0),
    author VARCHAR(120) NOT NULL CHECK (length(trim(author)) > 0),
    isbn VARCHAR(13) NOT NULL UNIQUE CHECK (isbn ~ '^97[89][0-9]{10}$'),
    publication_year INTEGER NOT NULL CHECK (publication_year BETWEEN 1 AND 9999),
    genre VARCHAR(30) NOT NULL CHECK (genre IN ('FICTION', 'FANTASY', 'SCIENCE', 'HISTORY', 'POETRY', 'TECHNOLOGY')),
    available BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
