spring:
  application:
    name: entrelinhas-catalog
  jackson:
    deserialization:
      accept-float-as-int: false
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: ENC(qdw1ULpoTSzWRuFcNFekJD25NksedEymQx2ZoARgeNWqna33wYAF42W7+I1AveE6)
    password: ENC(6cGhwm9ADPO5T25Z/M34Q3iKBkxu7p21PkOuJPkO131Imy9mn2iHJtsqHVa3S0oP)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

server:
  port: 8080

catalog:
  cors-origins: http://localhost:5173

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64
