spring:
  application:
    name: entrelinhas-catalog
  jackson:
    deserialization:
      accept-float-as-int: false
  datasource:
    url: jdbc:postgresql://localhost:5432/devdb
    username: rodrigo
    password: SUA_SENHA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

server:
  port: 8080

catalog:
  cors-origins: http://localhost:5173

springdoc:
  swagger-ui:
    path: /swagger-ui.html
