spring:
  application:
    name: entrelinhas-catalog
  jackson:
    deserialization:
      accept-float-as-int: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devdb}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

server:
  port: 8080

catalog:
  cors-origins: http://localhost:5173

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64
